export const ALL_DISCOUNT_REQUEST = 'ALL_DISCOUNT_REQUEST';
export const ALL_DISCOUNT_SUCCESS = 'ALL_DISCOUNT_SUCCESS';
export const ALL_DISCOUNT_FAIL = 'ALL_DISCOUNT_FAIL';

export const NEW_DISCOUNT_REQUEST = 'NEW_DISCOUNT_REQUEST';
export const NEW_DISCOUNT_SUCCESS = 'NEW_DISCOUNT_SUCCESS';
export const NEW_DISCOUNT_RESET = 'NEW_DISCOUNT_RESET';
export const NEW_DISCOUNT_FAIL = 'NEW_DISCOUNT_FAIL';

export const DELETE_DISCOUNT_REQUEST = 'DELETE_DISCOUNT_REQUEST';
export const DELETE_DISCOUNT_SUCCESS = 'DELETE_DISCOUNT_SUCCESS';
export const DELETE_DISCOUNT_RESET = 'DELETE_DISCOUNT_RESET';
export const DELETE_DISCOUNT_FAIL = 'DELETE_DISCOUNT_FAIL';

export const DISCOUNT_DETAILS_REQUEST = 'DISCOUNT_DETAILS_REQUEST';
export const DISCOUNT_DETAILS_SUCCESS = 'DISCOUNT_DETAILS_SUCCESS';
export const DISCOUNT_DETAILS_FAIL = 'DISCOUNT_DETAILS_FAIL';

export const UPDATE_DISCOUNT_REQUEST = 'UPDATE_DISCOUNT_REQUEST';
export const UPDATE_DISCOUNT_SUCCESS = 'UPDATE_DISCOUNT_SUCCESS';
export const UPDATE_DISCOUNT_RESET = 'UPDATE_DISCOUNT_RESET';
export const UPDATE_DISCOUNT_FAIL = 'UPDATE_DISCOUNT_FAIL';

export const ALL_DISCOUNT_PRODUCT_REQUEST = 'ALL_DISCOUNT_PRODUCT_REQUEST';
export const ALL_DISCOUNT_PRODUCT_SUCCESS = 'ALL_DISCOUNT_PRODUCT_SUCCESS';
export const ALL_DISCOUNT_PRODUCT_FAIL = 'ALL_DISCOUNT_PRODUCT_FAIL';

export const DELETE_DISCOUNT_PRODUCT_REQUEST = 'DELETE_DISCOUNT_PRODUCT_REQUEST';
export const DELETE_DISCOUNT_PRODUCT_SUCCESS = 'DELETE_DISCOUNT_PRODUCT_SUCCESS';
export const DELETE_DISCOUNT_PRODUCT_RESET = 'DELETE_DISCOUNT_PRODUCT_RESET';
export const DELETE_DISCOUNT_PRODUCT_FAIL = 'DELETE_DISCOUNT_PRODUCT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
